### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by liho26** [ricerati/proxy-checker-python#10]
Collecting pycurl
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
Building wheels for collected packages: pycurl
  Building wheel for pycurl (setup.py) ... error

**Comment by ricerati** [comment]
Which OS are you using? If you're using Windows you could try to install PycURL from [Christoph Gohlke's collection of Python Extension Package for Windows](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl).

To install a wheel, you use `pip install /path/to/wheel.whl`. Then install `proxy-checker` again with `pip install proxy-checker`.

Let me know if it resolves your issue.
