### ISSUE TITLE
Unable to install 

### ISSUE THREAD

**Issue by Jaynornj** [ricerati/proxy-checker-python#17]
Collecting proxy-checker
  Downloading proxy_checker-0.6-py3-none-any.whl (4.6 kB)
Collecting pycurl
  Downloading pycurl-7.45.2.tar.gz (234 kB)
     ---------------------------------------- 234.2/234.2 kB 2.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 10
  ╰─> [1 lines of output]
      Please specify --curl-dir=/path/to/built/libcurl
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by Natgho** [comment]
@ricerati please update the code.

Error solution;
```shell
sudo apt install libcurl4-openssl-dev libssl-dev
```

**Comment by Jaynornj** [comment]
Great, thank you! @Natgho

**Comment by Jaynornj** [comment]
Great, thank you!
