### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by amalroshan** [ricerati/proxy-checker-python#3]
I am getting this error at import line itself 

`from proxy_checker import ProxyChecker`

ImportError: cannot import name 'ProxyChecker' from partially initialized module 'proxy_checker' (most likely due to a circular import)

**Comment by ricerati** [comment]
This is not a problem with the package itself, but rather with your code. You can read about circular imports and how you can fix them on StackAbuse ([https://stackabuse.com/python-circular-imports/](https://stackabuse.com/python-circular-imports/)). If you're not able to find a solution, feel free to send me your code and I'd be happy to help.
