### ISSUE TITLE
Command errored out with exit status 10 when pip install proxy-checker

### ISSUE THREAD

**Issue by lobsik** [ricerati/proxy-checker-python#5]
why am i receive error when pip install proxy-checker

C:\Windows\system32>pip install proxy-checker
Collecting proxy-checker
  Using cached proxy_checker-0.4-py3-none-any.whl (4.3 kB)
Collecting pycurl
  Using cached pycurl-7.43.0.6.tar.gz (222 kB)
    ERROR: Command errored out with exit status 10:
     command: 'd:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.a
rgv[0] = '"'"'C:\\Users\\asus\\AppData\\Local\\Temp\\pip-install-8ho3d121\\pycur
l\\setup.py'"'"'; __file__='"'"'C:\\Users\\asus\\AppData\\Local\\Temp\\pip-insta
ll-8ho3d121\\pycurl\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__f
ile__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compil
e(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\asus\AppData\L
ocal\Temp\pip-pip-egg-info-naz5l16d'
         cwd: C:\Users\asus\AppData\Local\Temp\pip-install-8ho3d121\pycurl\
    Complete output (1 lines):
    Please specify --curl-dir=/path/to/built/libcurl
    ----------------------------------------
ERROR: Command errored out with exit status 10: python setup.py egg_info Check t
he logs for full command output.

**Comment by ricerati** [comment]
The error occurs when `PycURL` is being installed. You need to specify the path to `libcurl`.

```bash
Please specify --curl-dir=/path/to/built/libcurl
```

Alternatively, download and install `PycURL` from Christoph Gohlke's Windows Binaries for Python Extension Packages (https://www.lfd.uci.edu/~gohlke/pythonlibs/#pycurl) to have `libcurl` included in the package.

To install a WHL file you run the following command:

```
pip install /path/to/package.whl
```
