### ISSUE TITLE
nothing showed up

### ISSUE THREAD

**Issue by pocupine** [ricerati/proxy-checker-python#8]
Hi,
I have installed pycurl and I used these codes:

from proxy_checker import ProxyChecker
checker = ProxyChecker()
proxy='51.255.103.170:3129'
checker.check_proxy(proxy)

but nothing showed up in pycharm under windows 7. Any idea? Thanks.

**Comment by ZaViBiS** [comment]
![image](https://user-images.githubusercontent.com/40393850/109308027-2ba3cc00-784a-11eb-9ab5-7f36fe6bc14d.png)
maybe you have a problem with the https://api.ipify.org/.
Which may not work
https://github.com/ricerati/proxy-checker-python/issues/7

**Comment by ricerati** [comment]
`check_proxy` returns the proxy data. You've to print the value to see it.

If there's a problem with ipify, the IP address will be empty which causes the proxy type to always be `transparent`. A fix will be released for this soon, but it wouldn't cause the issue you're experiencing.

**Comment by pocupine** [comment]
I opened https://api.ipify.org/ which correctly showed my ip.
Ipython returned:

Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from proxy_checker import ProxyChecker

In [2]: checker=ProxyChecker()

In [3]: proxy='51.255.103.170:3129'

In [4]: checker.check_proxy(proxy)
Out[4]: False

**Comment by ricerati** [comment]
> I opened https://api.ipify.org/ which correctly showed my ip.
> Ipython returned:
> 
> Type 'copyright', 'credits' or 'license' for more information
> IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.
> 
> In [1]: from proxy_checker import ProxyChecker
> 
> In [2]: checker=ProxyChecker()
> 
> In [3]: proxy='51.255.103.170:3129'
> 
> In [4]: checker.check_proxy(proxy)
> Out[4]: False

When `False` is returned, it means the proxy doesn't work or that it didn't respond within the five second time limit.

**Comment by pocupine** [comment]
Weird. Possible when I was testing the code, the server was down for some time. And now is up and running again. Silly me. Thanks for the help and thanks for the great tool.

**Comment by pocupine** [comment]
Just an add-up that if you want to read line from a txt file, there are white spaces sometimes.
