### ISSUE TITLE
Returning False when used in a for loop

### ISSUE THREAD

**Issue by emrecandabak** [ricerati/proxy-checker-python#9]
`proxyList = open(proxyValues.proxypath).readlines()`
    `proxies = []`
    `for line in proxyList:`
        `proxies.append(line)`

    def testProxy(self, proxies=proxyList):
        checker = ProxyChecker()
        
        for proxy in proxies:
            print(checker.check_proxy(proxy)) 

That's the code I'm testing and everything worked fine when I called the "check_proxy" function in a single line without a loop. But when I put it in the for loop, It always returns False for the all proxies, and that happens too quick so I don't think it can be about the five seconds timeout. Looking for your help, thanks.

**Comment by ricerati** [comment]
`readlines()` keeps the line breaks (`\n`). Use `splitlines()` instead. For example:

```python3
checker = ProxyChecker()

with open('list.txt', 'r') as f:
    proxies = f.read().splitlines()

for proxy in proxies:
    print(checker.check_proxy(proxy))
```

**Comment by emrecandabak** [comment]
Oh didn't notice that, thank you so much! Now it works.

**Comment by hrabkin** [comment]
![Screenshot 2022-03-18 at 04 46 51](https://user-images.githubusercontent.com/2230377/158933979-ed9ba7ba-31fb-45d8-a676-8475f24d1568.png)
Why its False even without for-loop?
